name: Node.js test

on:
  push:
     tags:
       - v[0-9]+.[0-9]+.[0-9]+  # Triggers on any new tag (e.g., v1.0.0, v2.1.3)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run tests
        working-directory: ./travel-emission-api
        run: npm run test
